### ISSUE TITLE
Add Homepage

### ISSUE THREAD

**Issue by ayuhito** [fontsource/search-directory#1]
The directory itself is looking great and just needs a little polishing. However, it would make sense for us to have an initial homepage of a sort to introduce the project and give context to random viewers. 

Even as something as simple as this would serve to be useful: https://google-webfonts-helper.herokuapp.com/fonts

Feel free to assign this to yourself if you are addressing it, else I'll eventually pick this up after I'm finished with the implementation of variable fonts.

**Comment by jwr1** [comment]
Added a simple UI to the home page in commit https://github.com/fontsource/fontsource-search-directory/commit/42f4011fb2e78abe34d6d6c39de23c4fd8b14a19.
