### ISSUE TITLE
Add individual NPM and GitHub link to each page

### ISSUE THREAD

**Issue by ayuhito** [fontsource/search-directory#3]
Having a direct easy access link to the Fontsource pages on each font would be useful to improve site experience.

e.g. Roboto
https://www.npmjs.com/package/fontsource-roboto
https://github.com/fontsource/fontsource/tree/master/packages/roboto#readme

**Comment by jwr1** [comment]
Fixed with commit https://github.com/fontsource/search-directory/commit/0338575fc513aff4df0a47f702e699dab8f84d49.
