### ISSUE TITLE
Update documentation to v4

### ISSUE THREAD

**Issue by ayuhito** [fontsource/search-directory#45]
The main repository had a couple of [breaking changes](https://github.com/fontsource/fontsource/blob/master/CHANGELOG.md) which would leave the docs to be outdated.

Would it make sense to instead pull and parse the markdown files from Fontsource directly since our docs change quite a bit and it might be a lot of work manually updating the directory constantly to keep up?

**Comment by jwr1** [comment]
Fixed with commit https://github.com/fontsource/search-directory/commit/11e8179b85e029316393bb7b734566f149b55054.
