### ISSUE TITLE
Mobile Fixes

### ISSUE THREAD

**Issue by ayuhito** [fontsource/search-directory#61]
We seem to have major bugs when it comes to loading up the site on a smartphone (mine currently being an iPhone XS, but I'm sure other devices are being affected. I suppose we should look into it?

![image](https://user-images.githubusercontent.com/38220115/105641621-124be080-5e96-11eb-96e5-3340d6fa2fd3.jpeg)
![image](https://user-images.githubusercontent.com/38220115/105641625-17109480-5e96-11eb-9af5-fbee29000107.png)

**Comment by jwr1** [comment]
I also ran into this issue. Although I think it is a problem with ios because I checked both chrome and safari on an iphone and ipad, and it has this issue, but on desktop, android, and other devices I don't have this issue.

**Comment by ayuhito** [comment]
The Markdown can probably be resolved when migrating over to MDX, but the drawer from Material UI is out of my expertise to fix.

Personally, when working on #62, I would like to move over to [Chakra UI](https://chakra-ui.com/docs/getting-started) as it's my preference and I know it best. It would be pretty nice to emulate the same layout and style like the Chakra UI docs. However, I don't know if you're okay with me overwriting the frontend work.

I feel I should move over to Chakra because things such as integrating MDX and other features would become 10x harder for me to implement when migrating.

**Comment by jwr1** [comment]
I have fixed both of these problems in commit https://github.com/fontsource/search-directory/commit/fce640f2eff9eb315629295ce748d493652e253d. I will let you check it before closing this issue.
